[project]
name = "tubes3-ingfoloker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=37.3.0",
    "pymysql>=1.1.1",
    "pypdf2>=3.0.1",
    "pyqt6>=6.9.1",
    "python-dotenv>=1.1.0",
]
